# Generated by Django 5.1.3 on 2024-12-04 14:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.CharField(max_length=50, unique=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_allowed', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Tache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, unique=True, verbose_name='Tache')),
                ('description', models.TextField()),
                ('date_de_debut', models.DateField()),
                ('date_de_fin', models.DateField(blank=True, null=True)),
                ('priorite', models.CharField(choices=[('absolue', 'Absolue'), ('haute', 'Haute'), ('moyenne', 'Moyenne'), ('basse', 'Basse')], max_length=20)),
                ('statut', models.CharField(max_length=20)),
                ('avancement', models.IntegerField(default=0)),
                ('commentaires', models.TextField()),
                ('responsable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Tache',
                'ordering': ['-date_de_debut'],
            },
        ),
    ]
